spring:
  datasource:
    url: jdbc:mysql://34.143.176.77:3306/SportDB
    username: ecoDB
    password: eco@SAT2020
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    #printing parameter values in order
logging:
  level:
    org:
      hibernate:
        type: info
