package com.kkt.worthcalculation.model

data class GenerateExcelData(
    var b5: String = "",
    var c5: String = "",
    var d5: String = "",
    val f5: Int = 0,
    val g5: Int = 0,
    val k5: Int = 0,
    val l5: Int = 0,
    val m5: Int = 0,
    val n5: Int = 0,
    val o5: Int = 0,
    val p5: Int = 0,
    val s5: Int = 0,
    val t5: Int = 0,
    val u5: Int = 0,
    val v5: Int = 0,
    val w5: Int = 0,
    val x5: Int = 0,
    val y5: Int = 0,
    val z5: Int = 0,
    val ac5: Int = 0,
    val ad5: Int = 0,
    val ae5: Int = 0,
    val ag5: Int = 0,
    val ao5: Int = 0,
    val aq5: Int = 0,
)